services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always

  postgres:
    image: postgres:latest
    networks:
      - postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
